//import frc.robot.subsystems.ArmSubsystem.setRawPosition
//import frc.robot.subsystems.GrabberSubsystem.clamp
//import frc.robot.utils.MovingAverage.addValue
//import frc.robot.subsystems.ArmSubsystem.rotation
//import frc.robot.subsystems.ArmSubsystem.extension
//import frc.robot.subsystems.ArmSubsystem.setDesiredRotation
//import frc.robot.subsystems.ArmSubsystem.stopMotors
//import frc.robot.subsystems.ArmSubsystem.getPostionAngle
//import frc.robot.subsystems.ArmSubsystem.leftSide
//import frc.robot.subsystems.ArmSubsystem.getPostionExtension
//import frc.robot.subsystems.GrabberSubsystem.setMotorsSpeeds
//import frc.robot.subsystems.IntakeSubsystem.setBottomMotorSpeed
//import frc.robot.subsystems.IntakeSubsystem.setTopMotorSpeed
//import frc.robot.subsystems.swervedrive2.SwerveSubsystem.drive
//import frc.robot.subsystems.GrabberSubsystem.unclamp
//import frc.robot.subsystems.ArmSubsystem
//import java.util.function.DoubleSupplier
//import edu.wpi.first.wpilibj2.command.CommandBase
//import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard
//import frc.robot.utils.ArmPosition
//import java.util.function.IntSupplier
//import java.util.function.BooleanSupplier
//import frc.robot.subsystems.GrabberSubsystem
//import frc.robot.utils.MovingAverage
//import edu.wpi.first.math.controller.ArmFeedforward
//import frc.robot.Constants.Arm
//import frc.robot.subsystems.ArmSubsystem.Positions
//import frc.robot.subsystems.swervedrive2.SwerveSubsystem
//import com.ctre.phoenix.sensors.Pigeon2
//import frc.robot.commands.PidTurn
//import frc.robot.commands.PidZoom
//import frc.robot.commands.PidStrafe
//import frc.robot.commands.MoveTime
//import frc.robot.commands.MoveArmPosition
//import frc.robot.subsystems.IntakeSubsystem
//import frc.robot.Constants.Grabber
//import frc.robot.Constants.Intake
//import edu.wpi.first.wpilibj.DriverStation
//import edu.wpi.first.math.geometry.Translation2d